Vectorizer tfidf
retentioneering/retentioneering-tools pull request #20
Opened 2020-03-26 14:25 UTC by SynthaxWarrior

Added custom tokenizer, fixed some bugs in my implementation of custom tf-idf space cinstructed from the pre-built vocabulary.

2020-04-10 17:25 UTC, BillyYank reviewed
Часть комментов о архитектуре кода -- замена функций классами. Если хочется поскорее выкатить эти пулл реквесты, можно эти комменты на потом оставить в общей задаче рефакторинга.

2020-04-10 17:25 UTC, BillyYank commented on retentioneering/core/feature_extraction.py
> +    if 'index_col' not in kwargs:
Глядя на название frequency_embedder (а так же counts_embedder и так далее), хочется видеть класс, а не функцию. Из за того, что это реализовано как функции, есть повторяющийся код, например этот.

Есть предложение сдалать абстрактный класс Embedder, и наследоваться от него.

2020-04-10 17:25 UTC, BillyYank commented on retentioneering/core/utils.py
>          """
С учетом коммента выше, в эту функцию тогда будет передоваться не строка feature_type, а объект класса TfIdfEmbedder или CountEmbedder ...

2020-04-10 17:25 UTC, BillyYank commented on retentioneering/core/utils.py
> +        if 'vocab_pars' in kwargs.keys():
Не смог понять что такое vocab_pars

2020-04-10 17:25 UTC, BillyYank commented on retentioneering/core/utils.py
> +        t = data.split('~~')
Если это публичный метод, надо добавить описание. Либо сделать приватным (но описание тоже не помешает)

2020-04-10 17:25 UTC, BillyYank commented on retentioneering/core/utils.py
> +                    self_loops[url] = [0, 0, 0, 0, 0, 0]
Очень сложно понять код (у меня не получилось). Почему 6 нулей, что такое is_bad + 3. Что вообще такое is_bad? Потом except без указания типа ошибки (лучше вместо этого использовать if url not in self_loops: self_loops[url] = ...)

2020-04-10 17:25 UTC, BillyYank commented on retentioneering/core/utils.py
> +                self_loops[key][2] = val[1] / val[0]
Снова непонятные константы, но кажется они связаны с теми 6 нулями о которых я писал выше)

2020-04-10 20:37 UTC, SynthaxWarrior commented on retentioneering/core/feature_extraction.py
> +    if 'index_col' not in kwargs:
Макс предлагал подумать о серьёзной переделке репа, я думаю это замечание - к следующей его версии, где мы хотим сделать с большим использованием принципов ООП.

2020-04-10 20:44 UTC, SynthaxWarrior commented on retentioneering/core/utils.py
> +        if 'vocab_pars' in kwargs.keys():
Сделал комментарий в перечислении входных параметров функции

2020-04-10 20:44 UTC, SynthaxWarrior commented on retentioneering/core/utils.py
> +        t = data.split('~~')
Есть)

2020-04-15 12:36 UTC, SynthaxWarrior commented on retentioneering/core/utils.py
> +                    self_loops[url] = [0, 0, 0, 0, 0, 0]
Сделал описание, надеюсь понятней теперь.

2020-04-15 12:36 UTC, SynthaxWarrior commented on retentioneering/core/utils.py
> +                self_loops[key][2] = val[1] / val[0]
Да, с ними)

2020-04-15 16:28 UTC, BillyYank requested changes

2020-04-15 16:28 UTC, BillyYank commented on retentioneering/core/utils.py
> +        vocab_pars: dict, optional
vocab_pars --> vocab_params. А то больше на "пары" похоже

2020-04-15 16:28 UTC, BillyYank commented on retentioneering/core/utils.py
> +    def get_fraction(self, fraction=1, random_state=42):
Можно поменять название на что-то вроде get_fraction_equal, так как не очевидно, что будет одинаково хороших и плохих.
Но лучше обобщить, добавив параметр fraction_bad, (другой в любом случае должен называться fraction_good).
Для дальнейшей простоты использования подумай над тем чтоб возвращать не два датафрейма, а один с меткой.

2020-04-15 16:28 UTC, BillyYank commented on retentioneering/core/utils.py
> +        return (self._obj[self._obj[self._index_col()].isin([good_users[i] for i in good_idx])], \
Можно проще:

fraction_size = int(len(good_users) * fraction)
good_users_ids = np.random.choice(self.get_positive_users(), fraction_size, replace=False)
bad_users_ids = np.random.choice(self.get_negative_users(), fraction_size, replace=False)
good_users = self._obj.merge(pd.DataFrame(data=good_users_ids, columns=self._index_col()), how='inner', on=self._index_col())
bad_users = self._obj.merge(pd.DataFrame(data=bad_users_ids, columns=self._index_col()), how='inner', on=self._index_col())
return good_users, bad_users

.isin([good_users[i] for i in good_idx]) -- поиск работает за линию, можно за логарифм если использовать множество

2020-04-15 16:28 UTC, BillyYank commented on retentioneering/core/utils.py
> +        good_idx = np.random.choice(range(len(good_users)), int(len(good_users) * fraction), replace=False).astype(
Если плохих меньше чем хороших, то будет не поровну

2020-04-15 16:28 UTC, BillyYank commented on retentioneering/core/utils.py
> +    def loop_search(self, data, self_loops, event_list, is_bad):
Эта функция не нужна

2020-04-15 16:28 UTC, BillyYank commented on retentioneering/core/utils.py
> +                            columns=['Sequence', 'Good', 'Lost', 'Coefficient', 'Good_no_duplicates',
sequence_num, good_cycles_num,... хотя бы так. Непонятные названия

2020-04-19 18:26 UTC, merged